// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FestivalInfo 节日信息结构（返回给前端）
 */
export class FestivalInfo {
    "name": string;
    "days": number;
    "type": string;

    /** Creates a new FestivalInfo instance. */
    constructor($$source: Partial<FestivalInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("days" in $$source)) {
            this["days"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FestivalInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FestivalInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FestivalInfo($$parsedSource as Partial<FestivalInfo>);
    }
}
