// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService 配置服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig 获取配置
 */
export function GetConfig(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(949429127).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Load 加载配置
 */
export function Load(): $CancellablePromise<void> {
    return $Call.ByID(663828459);
}

/**
 * Save 保存配置
 */
export function Save(): $CancellablePromise<void> {
    return $Call.ByID(1374938246);
}

/**
 * UpdateConfig 更新配置
 */
export function UpdateConfig(config: $models.Config | null): $CancellablePromise<void> {
    return $Call.ByID(2353698052, config);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
