// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FestivalService 节日服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetNextFestival 获取下一个节日
 */
export function GetNextFestival(): $CancellablePromise<$models.FestivalInfo | null> {
    return $Call.ByID(2064706382).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FestivalInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
