// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config 应用配置
 */
export class Config {
    /**
     * 上班时间（小时）
     */
    "workStartHour": number;

    /**
     * 下班时间（小时）
     */
    "workEndHour": number;

    /**
     * 月薪
     */
    "monthlySalary": number;

    /**
     * 发薪日
     */
    "payday": number;

    /**
     * 窗口透明度 0-1
     */
    "opacity": number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("workStartHour" in $$source)) {
            this["workStartHour"] = 0;
        }
        if (!("workEndHour" in $$source)) {
            this["workEndHour"] = 0;
        }
        if (!("monthlySalary" in $$source)) {
            this["monthlySalary"] = 0;
        }
        if (!("payday" in $$source)) {
            this["payday"] = 0;
        }
        if (!("opacity" in $$source)) {
            this["opacity"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * FestivalInfo 节日信息结构（返回给前端）
 */
export class FestivalInfo {
    "name": string;
    "days": number;
    "type": string;

    /** Creates a new FestivalInfo instance. */
    constructor($$source: Partial<FestivalInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("days" in $$source)) {
            this["days"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FestivalInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FestivalInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FestivalInfo($$parsedSource as Partial<FestivalInfo>);
    }
}
